### ISSUE TITLE
Missing encode on client handshake and decode on server handshake.

### ISSUE THREAD

**Issue by Falkirks** [PocketMine/RakLib#10]
I need these methods for a project and although they are not needed for PocketMine-MP, this library is a

> UDP network library that follows the RakNet protocol for PHP

So I would personally expect to be able to decode and encode these packets. 
- https://github.com/PocketMine/RakLib/blob/master/protocol/CLIENT_HANDSHAKE_DataPacket.php is missing a proper encode method.
- https://github.com/PocketMine/RakLib/blob/master/protocol/SERVER_HANDSHAKE_DataPacket.php is missing a proper decode method.

I would implement this myself, but I am not sure where to stick the`getDataArray` and `putDataArray` methods.

**Comment by shoghicp** [comment]
Oh, I think you need even more methods (for a client implementation of RakLib).

The fact is that RakNet servers do extra checking and some parts of the protocol are still not known.

**Comment by Falkirks** [comment]
Granted, but it would be nice to have enough to fool PocketMine or another server implementation. Even with what is known these methods could be implemented to a state which functions and represents the currently known protocol.

**Comment by shoghicp** [comment]
I mean that it's not JUST what you said, but needs more work. And the problem that we don't fully understand that part still slows down things :S

**Comment by jython234** [comment]
@Falkirks I have implemented both of these in BlockClient, you could take a look at that.

**Comment by jython234** [comment]
@Falkirks #14
