### ISSUE TITLE
Rail booster

### ISSUE THREAD

**Issue by Fightingfire** [PocketMine/RakLib#17]
i have this:
[RakLib Thread #139987135751936] Blocked 192.168.x.x for 5 second

**Comment by jython234** [comment]
That means that a player with that IP address is sending too many packets
at once to the server, so raklib ignores all its packets for 5 sevonds.

**Comment by PEMapModder** [comment]
@jython234 more likely, server encountered internal errors, throws exception, and RakLib considers that as the client sending wrong data to attack the server.

**Comment by jython234** [comment]
@PEMapModder its possible, forgot it did that.
